### ISSUE TITLE
Cannot use with proxy

### ISSUE THREAD

**Issue by dagobert** [Superslub/AGI_Reverse_Lookup_DACH#11]
It would be great to be able to use the script behind a PROXY. For this you would have to giveup using `LWPx::ParanoidAgent`. I would really appreciate it.

**Comment by Superslub** [comment]
The latest version uses mechanize for scraping (DE/AT/CH). So you can easily add your proxy.

**Comment by Superslub** [comment]
Add your proxy config at line 97+
