### ISSUE TITLE
Unknown number in Oertliche causes error insteadof hitempty

### ISSUE THREAD

**Issue by dagobert** [Superslub/AGI_Reverse_Lookup_DACH#13]
== Problem ==

When a german number is searched in oertliche and it is not found, the script falls into the `catch` statement and reports an error.

== Cause ==

My proxy reports a 410 returned by the oertliche webserver.

== Possible solution ==

I will send a pull request soon.

**Comment by Superslub** [comment]
Thx!

**Comment by dagobert** [comment]
No problem
