### ISSUE TITLE
Konfiguratn in extra Datei

### ISSUE THREAD

**Issue by Koch-EDV** [Superslub/AGI_Reverse_Lookup_DACH#2]
Hallo,

ich habe dein Script gerade Installiert, scheint soweit zu laufen.
Ich würde mir aber 2 Dinge wünschen, hier erst mal das erste und sicherlich auch das leichtere.
Könnte man die Konfig in eine Eigene Datei legen, So ist es leichter das Script upzudaten.

**Comment by Superslub** [comment]
Wenn das jemand implementiert, so kann das sicher aufgenommen werden. Ich sehe da (für mich) allerdings keinen Bedarf. Gute Idee aber allemal ...
