### ISSUE TITLE
Freepbx hat ein Frontend um ein Phonebook zu Verwalten.

### ISSUE THREAD

**Issue by Koch-EDV** [Superslub/AGI_Reverse_Lookup_DACH#3]
Ich hatte so ein ähnliches script laufen.
Das hat die Einträge zum cachen in diese DB abgelegt. Hatte den Vorteil das man die Einträge editieren könnte. Würdest du das ggf. auch Implementieren?

**Comment by Superslub** [comment]
Ein Frontend dafür zu bauen wäre aufwendiger als das Skript selbst. Man kann aber z.Z. mit den Asterisk-eigenen Hilfsmitteln die Datenbankeinträge editieren, auch hier liegt der Cache in der AsteriskDB.
(Unkomfortabel aber, zugegebenermaßen.)

**Comment by Koch-EDV** [comment]
Sorry falsch verstanden Frontend ist schon da. Es geht darum die such Ergebnisse in die richtige Datenbank zu schreiben. Ich such ihnen das raus. 
--
Gesendet von meinem Smartphone
Koch EDV­
Auweg 2 - 35638 Leun / Biskirchen­
www.koch-edv.net­
Fon: ­+49 6473 799515 - 0­
UstID: DE248337904 ­
Sitz des Unternehmens: Leun­
Geschäftsführer: Alexander Koch­ Freitag, 21 August 2015, 11:02AM +02:00 von Superslub < notifications@github.com> :
