### ISSUE TITLE
Falscher Country-Code 04 statt +49 oder 0049

### ISSUE THREAD

**Issue by Ciatronical** [Superslub/AGI_Reverse_Lookup_DACH#9]
Hey,

ich habe in meine extension.ael folgenden Code eingegeben
`AGI(reverse_search.agi, ${CALLERID(num)});`
`Set(CALLERID(name)=${RESULTREV}); `
`Verbose( 1,  Ergebnis  reverse_search: ${RESULTREV}  );`

Leider erhalte ich folgende Fehlermeldung
`  == reverse_search.agi, +4933435884444: RS:   number(std) = (004933435884444)`
`  == reverse_search.agi, +4933435884444: RS:       country = (04)`
` reverse_search.agi, +4933435884444: RS: Staticsearch(3): DBs not configured or deactivated`
` reverse_search.agi, +4933435884444: RS: Cachesearch(5): Name/TS-Entry not found -> search online004933435884444`
` reverse_search.agi, +4933435884444: RS: Number from unhandled country: 04`
` reverse_search.agi, +4933435884444: RS: Onlinesearch(4): ERROR - Onlinesearch failed`
` -- <SIP/inter-data-00000388>AGI Script reverse_search.agi completed, returning 0`

Der Test in der Console mit "#bash check.bash" funktioniert einwandfrei.
Meine Asterisk-Version lautet: 16.2.1~dfsg-2ubuntu1 

Woran kann das liegen?
Viele Grüße
Ronny

**Comment by Ciatronical** [comment]
Ich konnte den Fehler beseitigen in dem ich die  Zeile 174 wie folgt geändert habe:
`my $cp = substr($number,length($interprefix1)+1,2);`  quick and dirty

Danach kam der nächste Fehler:" HTTP-Request failed (396): 500 Can't verify SSL peers without knowing which Certificate Authorities to trust"

Wünschenswert wäre hier ein kleines Script welches die Installation der benötigten Perlpakete prüft.
Asterisk::AGI , String::Util, LWPx::ParanoidAgent , Mozilla::CA, etc

Oder in der README.txt dokumentieren.

Vielen Dank für die Mühe und dieses wunderbare Script..

Asterisk ruft es täglich mindestens 30 mal auf...

**Comment by dagobert** [comment]
> Ich konnte den Fehler beseitigen in dem ich die Zeile 174 wie folgt geändert habe: `my $cp = substr($number,length($interprefix1)+1,2);` quick and dirty

Ich glaube nicht, daß das eine Lösung ist, die korrekt ist. In Zeile 160 steht:

`# wenn Nummer mit interprefix1 beginnt, dieses durch interprefix2 ersetzen`

Das würde bedeuten, dass die Nummern (siehe auch Verbose Ausgabe) alle mit 00 beginnen sollen. Ich gehe davon aus, dass es ein Typo ist und in Zeile 174 eigentlich wie folgt heißen müsste:

`my $cp = substr($number,length($interprefix2),2);`

Die "00" werden dann abgeschnitten. In Deinem Fall hast Du das "+", also ein Zeichen plus ein weiteres Zeichen abgeschnitten. Das passt nur zufällig.

Ich werde einen Pull request schreiben.

**Comment by realslub** [comment]
(Ich bin "superslub" - habe aber nach all den Jahren der Inaktivität Probleme mit der E-Mail-Adresse, die ich hier bei Github hinterlegt habe und kann aktuell leider nur so antworten.)

Erst einmal: Danke für den Hinweis und den Pull-Request.

Ich habe mit gestern hingesetzt und das Skript etwas aktualisiert. "Programmieren" mit nano auf dem pi ist echt toll :/

Das Scraping funktioniert jetzt per XPath (einfacher zu handhaben und zu aktualisieren). Zum Holen der Inhalte wird jetzt mechanize genutzt,

Statt Klicktel gibt es jetzt 11880.

DE/AT/CH sollte jetzt wieder funktionieren (wenngleich auch FR und IT noch als Function drin sind)

Ich kann aktuell keinen push machen, da ich auf das Repository nicht zugreifen kann. Deshalb hier die aktualisierte Version (sorry, als "zip" - Github akzeptiert keine .agi-Dateien):
[AGI_Reverse_Lookup_DACH.zip](https://github.com/user-attachments/files/15749581/AGI_Reverse_Lookup_DACH.zip)

**Comment by Superslub** [comment]
OK, Account zurückgeholt und Version aktualisiert.

Ich hoffe es funktioniert bei euch alles
